#ifndef TOPICSENUM_H
#define TOPICSENUM_H

enum Topics {
    ALIGNMENT,
    COMBINATORICS,
    CMS,
    DIVIDEANDCONQUER,
    DYNAMICPROGRAMMING,
    GENOMEASSEMBLY,
    GENOMEREARRANGEMENTS,
    GRAPHALGORITHMS,
    GRAPHS,
    HEREDITY,
    PHYLOGENY,
    POPULATIONDYNAMICS,
    PROBABILITY,
    SETTHEORY,
    SORTING,
    STRINGALGORITHMS
};

#endif // TOPICSENUM_H
